name: Update Roadmap

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  update_roadmap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Roadmap
        env:
          ROADMAP_BADGE_URL: "https://api.roadmap.sh/v1-badge/tall/64bce9c08b7b0932737deff9?variant=dark"
          ROADMAP_SH_URL: "https://roadmap.sh"
        run: |
          # Download the badge image
          wget -qO roadmap-badge.svg $ROADMAP_BADGE_URL

          # Commit the badge image to the repository
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add roadmap-badge.svg
          git commit -m "Update roadmap badge [skip ci]"
          git push

          # Update the README with the badge
          # echo '<a align="left" href="$ROADMAP_SH_URL"><img src="roadmap-badge.svg" alt="roadmap.sh"/></a>' > new_readme.md
          # cat README.md >> new_readme.md
          # mv new_readme.md README.md

          # Commit the updated README to the repository
          # git add README.md
          # git commit -m "Update README with roadmap badge [skip ci]"
          # git push
